---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: spring-boot
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: spring-boot@sha256:4087bfa1711d48acaebd903b6f0aebbac290b14f3bfa9c7f1bd5381a58d43f3b
        namespace: antonio-cipollaro-code
      name: 1.1.0
